routes/web.php
<?php

use App\Http\Controllers\AdminPemesananController;
use App\Http\Controllers\BankController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DriverfeeController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\JasaController;
use App\Http\Controllers\KategoriPemasukanController;
use App\Http\Controllers\KategoriPengeluaranController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\MobilController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\PengembalianController;
use App\Http\Controllers\RentalController;
use App\Http\Controllers\TransaksiPemasukanController;
use App\Http\Controllers\TransaksiPengeluaranController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();
Route::get('/', [FrontController::class, 'pemesanan'])->name('home');

Route::get('/fetch-durasi', [RentalController::class, 'durasiFetch'])->name('durasiFetch');

Route::get('/service/rental', [RentalController::class, 'mobil'])->name('rental.mobil');
Route::get('/service/rental/pemesanan', [RentalController::class, 'pemesanan'])->name('rental.pemesanan');
Route::post('/service/rental/pemesanan/store', [FrontController::class, 'storePemesanan'])->name('rental.pemesanan.store');
Route::get('//service/rental/pemesanan/detail', [FrontController::class, 'detailPemesanan'])->name('rental.pemesanan.detail');


Route::get('/fganti_psswrd', [HomeController::class, 'fganti_psswrd'])->name('fganti_psswrd');
Route::put('/update_psswrd/{user}', [HomeController::class, 'update_psswrd'])->name('update_psswrd');

Route::group(['middleware' => ['auth']], function () {

    Route::get('/home', [HomeController::class, 'home'])->name('home');

    Route::get('/profile', [HomeController::class, 'profile'])->name('profile');

    Route::get('/laporan/', [ReportController::class, 'index'])->name('laporan.index');

    Route::get('/pemesanan/', [AdminPemesananController::class, 'index'])->name('pemesanan.index');
    Route::get('/pemesanan/{id}/detail', [AdminPemesananController::class, 'detail'])->name('pemesanan.detail');

    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    // Route::resource('menu', MenuController::class);
    Route::resource('customer', CustomerController::class);
    Route::resource('inventory', InventoryController::class);
    Route::resource('order', OrderController::class);
    Route::resource('finishorder', PengembalianController::class);
    Route::resource('invoice', InvoiceController::class);

    Route::resource('kategori/pemasukan', KategoriPemasukanController::class)->names('kategori.pemasukan');
    Route::resource('kategori/pengeluaran', KategoriPengeluaranController::class)->names('kategori.pengeluaran');

    Route::resource('transaksi/pemasukan', TransaksiPemasukanController::class)->names('transaksi.pemasukan');
    Route::resource('transaksi/pengeluaran', TransaksiPengeluaranController::class)->names('transaksi.pengeluaran');

    Route::resource('mobil',MobilController::class);
    Route::resource('kota',KotaController::class);
    Route::resource('jasa',JasaController::class);
    Route::resource('bank',BankController::class);
    Route::resource('driverfee',DriverfeeController::class);


    Route::get('/getphoto', [InventoryController::class, 'getphoto']);
    Route::get('/getcustomer', [CustomerController::class, 'getcustomer']);
    Route::get('/getinventory', [InventoryController::class, 'getinventory']);
    Route::get('/cetakinv/{no_inv}', [InvoiceController::class, 'cetak']);

    Route::get('/pengembalian/{order_id}', [OrderController::class, 'pengembalian']);
    Route::get('/invoicing/{id}', [PengembalianController::class, 'invoicing'])->name('report.invoicing');
});

app/Models/Mobil.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Mobil extends Model
{
    use HasFactory;
}

app/Http/Controllers/MobilController.php
<?php

namespace App\Http\Controllers;

use App\Models\Customer;
use App\Models\Menu;
use App\Models\Mobil;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\View\View;

class MobilController extends Controller
{
    public function index(): View
    {

        $mobilList = Mobil::all();
      
        $dt = [
            'menu' => 'Data Kendaraan',
            'title' => 'List Kendaraan',
            'mobilList' => $mobilList,
            
        ];
        $menu = [
            'menu' => Menu::all()->sortBy('urutan'),
        ];
        return view('mobil.index', compact('dt', 'menu'));
    }

    public function create(): View
    {
      
        $dt = [
            'menu' => 'Kelola Kendaraan',
            'title' => 'Tambah Kendaraan Baru',
            
            
        ];
        $menu = [
            'menu' => Menu::all()->sortBy('urutan'),
        ];
        return view('mobil.create', compact('dt', 'menu'));
    }

    public function store(Request $request)
    {

        $rules = [
            
            'merek'     => 'required',
            'tipe'      => 'required',
            'warna'     => 'required',
            'harga_6'     => 'required',
            'harga_12'     => 'required',
            'harga_24'     => 'required',
            'harga_day'     => 'required',
            
            

		];

		$errorMessages = [
            'required' => 'Kolom harus diisi',
        ];

        $this->validate($request, $rules, $errorMessages);

        $mobil = new Mobil();

        $mobil->nopol = $request->nopol;
        $mobil->merek = $request->merek;
        $mobil->tipe = $request->tipe;
        $mobil->warna = $request->warna;
        $mobil->harga_6 = $request->harga_6;
        $mobil->harga_12 = $request->harga_12;
        $mobil->harga_24 = $request->harga_24;
        $mobil->harga_day = $request->harga_day;
        $mobil->status = 1;


        $mobil->save();

        return redirect()->route('mobil.index')->with('success', 'Data kendaraan berhasil disimpan');

    }

    public function edit($id)
    {

        $mobil = Mobil::find($id);

        $dt = [
            'menu' => 'Kelola Kendaraan',
            'title' => 'Tambah Kendaraan Baru',
            
        ];
        $menu = [
            'menu' => Menu::all()->sortBy('urutan'),
        ];

        return view('mobil.edit', compact('dt', 'menu','mobil'));

    }

    public function update(Request $request, $id)
    {
        $mobil = Mobil::find($id);

        $rules = [
            
            'merek'     => 'required',
            'tipe'      => 'required',
            'warna'     => 'required',
            'harga_6'     => 'required',
            'harga_12'     => 'required',
            'harga_24'     => 'required',
            'harga_day'     => 'required',
            
            

		];

		$errorMessages = [
            'required' => 'Kolom harus diisi',
        ];

        $this->validate($request, $rules, $errorMessages);

       

        $mobil->nopol = $request->nopol;
        $mobil->merek = $request->merek;
        $mobil->tipe = $request->tipe;
        $mobil->warna = $request->warna;
        $mobil->harga_6 = $request->harga_6;
        $mobil->harga_12 = $request->harga_12;
        $mobil->harga_24 = $request->harga_24;
        $mobil->harga_day = $request->harga_day;

        $mobil->save();

        return redirect()->route('mobil.index')->with('success', 'Data kendaraan berhasil diperbaharui');
    }

    public function destroy($id)
    {
        $mobil = Mobil::find($id);
        $mobil->delete();

        return redirect()->route('mobil.index')->with('success', 'Data kendaraan berhasil dihapus');
    }
}

app/View/Components/Stats/Mobil.php
<?php

namespace App\View\Components\Stats;

use App\Models\Mobil as ModelsMobil;
use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Mobil extends Component
{
    /**
     * Create a new component instance.
     */
    public $total;
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        $this->total = ModelsMobil::count();
        return view('components.stats.mobil');
    }
}

resources/views/mobil/create.blade.php
@extends('shared_pages.layout')
@section('content')
    <div class="card">
        <div class="card-header">
            <h5>{{ $dt['title'] }}</h5>
        </div>
        <div class="card-body">
            <form action="{{ route('mobil.store') }}" name="myForm" method="POST" onsubmit="return validateForm()">
                @csrf
                @method('POST')
                <!-- Page Heading -->
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <div class="d-sm-flex">
                        <a href="{{ route('mobil.index') }}" class="btn btn-md btn-circle btn-outline-danger">
                            <i class="bi bi-skip-backward-fill"></i> Back
                        </a>
                        &nbsp;
                    </div>
                    {{-- <button type="submit" class="btn btn-outline-success btn-md btn-icon-split">
                        Submit Order <i class="bi bi-sd-card-fill"></i>
                    </button> --}}
                </div>

                <!-- content -->
                <div class="row">
             
                    <div class="col-lg-12">
                        <div class="card border-bottom-primary shadow mb-4">
                            <div class="card-header py-3 bg-orange">
                                <h6 class="m-0 font-weight-bold text-white">Data Kendaraan</h6>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Nomor Polisi</label>
                                            <input type="text" class="form-control" name="nopol" value="{{ old('nopol') }}">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Merek</label>
                                            <input type="text" class=" form-control @error('merek') is-invalid @enderror" name="merek" value="{{ old('merek') }}">
                                            @error('merek')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Tipe</label>
                                            <input type="text" class=" form-control @error('tipe') is-invalid @enderror" name="tipe" value="{{ old('tipe') }}">
                                            @error('tipe')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Warna</label>
                                            <input type="text" class=" form-control @error('warna') is-invalid @enderror" name="warna" value="{{ old('warna') }}">
                                            @error('warna')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-3">
                                        <div class="form-group">
                                            <label class="mt-2">Harga 6 jam</label>
                                            <input type="text" class=" form-control @error('harga_6') is-invalid @enderror" name="harga_6" value="{{ old('harga_6') }}">
                                            @error('harga_6')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-3">
                                        <div class="form-group">
                                            <label class="mt-2">Harga 12 jam</label>
                                            <input type="text" class=" form-control @error('harga_12') is-invalid @enderror" name="harga_12" value="{{ old('harga_12') }}">
                                            @error('harga_12')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-3">
                                        <div class="form-group">
                                            <label class="mt-2">Harga 24 jam</label>
                                            <input type="text" class=" form-control @error('harga_24') is-invalid @enderror" name="harga_24" value="{{ old('harga_24') }}">
                                            @error('harga_24')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-3">
                                        <div class="form-group">
                                            <label class="mt-2">Harga Perday</label>
                                            <input type="text" class=" form-control @error('harga_day') is-invalid @enderror" name="harga_day" value="{{ old('harga_day') }}">
                                            @error('harga_day')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                  
                                </div>

                                <button type="submit" class="btn btn-outline-success btn-md btn-icon-split">
                                    Submit Kendaraan <i class="bi bi-sd-card-fill"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                  
                </div>
            </form>
        </div>
    </div>
    <script>
       
    </script>
@endsection

resources/views/mobil/edit.blade.php
@extends('shared_pages.layout')
@section('content')
    <div class="card">
        <div class="card-header">
            <h5>{{ $dt['title'] }}</h5>
        </div>
        <div class="card-body">
            <form action="{{ route('mobil.update',$mobil->id) }}" name="myForm" method="POST" onsubmit="return validateForm()">
                @csrf
                @method('PATCH')
                <!-- Page Heading -->
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <div class="d-sm-flex">
                        <a href="{{ route('mobil.index') }}" class="btn btn-md btn-circle btn-outline-danger">
                            <i class="bi bi-skip-backward-fill"></i> Back
                        </a>
                        &nbsp;
                    </div>
                    {{-- <button type="submit" class="btn btn-outline-success btn-md btn-icon-split">
                        Submit Order <i class="bi bi-sd-card-fill"></i>
                    </button> --}}
                </div>

                <!-- content -->
                <div class="row">
             
                    <div class="col-lg-12">
                        <div class="card border-bottom-primary shadow mb-4">
                            <div class="card-header py-3 bg-orange">
                                <h6 class="m-0 font-weight-bold text-white">Data Kendaraan</h6>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Nomor Polisi</label>
                                            <input type="text" class="form-control" name="nopol" value="{{ old('nopol') ? old('nopol')  : $mobil->nopol   }}">
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Merek</label>
                                            <input type="text" class=" form-control @error('merek') is-invalid @enderror" name="merek" value="{{ old('merek') ? old('merek') : $mobil->merek }}">
                                            @error('merek')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Tipe</label>
                                            <input type="text" class=" form-control @error('tipe') is-invalid @enderror" name="tipe" value="{{ old('tipe') ? old('tipe') : $mobil->tipe }}">
                                            @error('tipe')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Warna</label>
                                            <input type="text" class=" form-control @error('warna') is-invalid @enderror" name="warna" value="{{ old('warna') ? old('warna') : $mobil->warna }}">
                                            @error('warna')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-3">
                                        <div class="form-group">
                                            <label class="mt-2">Harga 6 Jam</label>
                                            <input type="text" class=" form-control @error('harga_6') is-invalid @enderror" name="harga_6" value="{{ old('harga_6') ? old('harga_6') : $mobil->harga_6 }}">
                                            @error('harga_6')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-3">
                                        <div class="form-group">
                                            <label class="mt-2">Harga 12 Jam</label>
                                            <input type="text" class=" form-control @error('harga_12') is-invalid @enderror" name="harga_12" value="{{ old('harga_12') ? old('harga_12') : $mobil->harga_12 }}">
                                            @error('harga_12')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-3">
                                        <div class="form-group">
                                            <label class="mt-2">Harga 24 Jam</label>
                                            <input type="text" class=" form-control @error('harga_24') is-invalid @enderror" name="harga_24" value="{{ old('harga_24') ? old('harga_24') : $mobil->harga_24 }}">
                                            @error('harga_24')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-3">
                                        <div class="form-group">
                                            <label class="mt-2">Harga Perday</label>
                                            <input type="text" class=" form-control @error('harga_day') is-invalid @enderror" name="harga_day" value="{{ old('harga_day') ? old('harga_day') : $mobil->harga_day }}">
                                            @error('harga_day')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>


                                  
                                </div>

                                <button type="submit" class="btn btn-outline-success btn-md btn-icon-split">
                                    Submit Kendaraan <i class="bi bi-sd-card-fill"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                  
                </div>
            </form>
        </div>
    </div>
    <script>
       
    </script>
@endsection

resources/views/mobil/index.blade.php
@extends('shared_pages.layout')
@section('content')
    <section class="section">
        <div class="card">
            <div class="card-header text-end">
                <h4>{{ $dt['title'] }}</h4>
            </div>
            <div class="card-body">
                @if ($message = Session::get('success'))
                    <div class="mb-3 pl-3 pr-3">
                        <div class="alert alert-success alert-dismissible show fade">
                            <i class="far fa-fw fa-bell"></i> {{ $message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                @endif
                @can('peminjaman-create')
                    <a href="{{ route('mobil.create') }}" class="btn btn-outline-success mb-5">
                        <i class="bi bi-plus-circle"></i> Buat Order Baru
                    </a>
                @endcan
                <div class="table-responsive">
                    <table class="table" id="table1">
                        <thead>
                            <tr class="bg-orange text-light">
                                <th>No</th>
                                <th>Nopol</th>
                                <th>Merek</th>
                                <th>Tipe</th>
                                <th>Warna</th>
                                <th>6 Jan</th>
                                <th>12 Jam</th>
                                <th>24 Jam</th>
                                <th>Per day</th>
                                <th>Status</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $k = 0; ?>
                            @forelse ($dt['mobilList'] as $p)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                   
                                   
                                    <td>{{ $p->nopol }}</td>
                                    <td>{{ $p->merek }}</td>
                                    <td>{{ $p->tipe }}</td>
                                    <td>{{ $p->warna }}</td>
                                    <td>{{ $p->harga_6 }}</td>
                                    <td>{{ $p->harga_12 }}</td>
                                    <td>{{ $p->harga_24 }}</td>
                                    <td>{{ $p->harga_day }}</td>
                                    <td>
                                        @if ($p->status == 1)
                                            Tersedia
                                        @else
                                            Disewa
                                        @endif
                                    </td>
                                   
                                    
                                    <td>

                                        <div class="d-flex">

                                            <a class="btn btn-sm btn-primary me-1" href="{{ route('mobil.edit', $p->id) }}"
                                                title="Edit Customer"><i class="bi bi-pencil"></i></a>
                                           
                                            <form onsubmit="return confirm('Benar akan meghapus data ini ?')"
                                                action="{{ route('mobil.destroy', $p->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                
                                                    <button type="submit" class="btn btn-sm btn-danger" title="Delete"><i
                                                            class="bi bi-x"></i></button>
                                                
                                            </form>

                                        </div>
                                        
                                    </td>
                                </tr>
                                <?php $k++; ?>
                            @empty
                                <tr>
                                    <td colspan="7" class="text-danger text-center">Data order rental belum ada</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <script>
       
    </script>
@endSection