routes/web.php
<?php

use App\Http\Controllers\AdminPemesananController;
use App\Http\Controllers\BankController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DriverfeeController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\JasaController;
use App\Http\Controllers\KategoriPemasukanController;
use App\Http\Controllers\KategoriPengeluaranController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\MobilController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\PengembalianController;
use App\Http\Controllers\RentalController;
use App\Http\Controllers\TransaksiPemasukanController;
use App\Http\Controllers\TransaksiPengeluaranController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();
Route::get('/', [FrontController::class, 'pemesanan'])->name('home');

Route::get('/fetch-durasi', [RentalController::class, 'durasiFetch'])->name('durasiFetch');

Route::get('/service/rental', [RentalController::class, 'mobil'])->name('rental.mobil');
Route::get('/service/rental/pemesanan', [RentalController::class, 'pemesanan'])->name('rental.pemesanan');
Route::post('/service/rental/pemesanan/store', [FrontController::class, 'storePemesanan'])->name('rental.pemesanan.store');
Route::get('//service/rental/pemesanan/detail', [FrontController::class, 'detailPemesanan'])->name('rental.pemesanan.detail');


Route::get('/fganti_psswrd', [HomeController::class, 'fganti_psswrd'])->name('fganti_psswrd');
Route::put('/update_psswrd/{user}', [HomeController::class, 'update_psswrd'])->name('update_psswrd');

Route::group(['middleware' => ['auth']], function () {

    Route::get('/home', [HomeController::class, 'home'])->name('home');

    Route::get('/profile', [HomeController::class, 'profile'])->name('profile');

    Route::get('/laporan/', [ReportController::class, 'index'])->name('laporan.index');

    Route::get('/pemesanan/', [AdminPemesananController::class, 'index'])->name('pemesanan.index');
    Route::get('/pemesanan/{id}/detail', [AdminPemesananController::class, 'detail'])->name('pemesanan.detail');

    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    // Route::resource('menu', MenuController::class);
    Route::resource('customer', CustomerController::class);
    Route::resource('inventory', InventoryController::class);
    Route::resource('order', OrderController::class);
    Route::resource('finishorder', PengembalianController::class);
    Route::resource('invoice', InvoiceController::class);

    Route::resource('kategori/pemasukan', KategoriPemasukanController::class)->names('kategori.pemasukan');
    Route::resource('kategori/pengeluaran', KategoriPengeluaranController::class)->names('kategori.pengeluaran');

    Route::resource('transaksi/pemasukan', TransaksiPemasukanController::class)->names('transaksi.pemasukan');
    Route::resource('transaksi/pengeluaran', TransaksiPengeluaranController::class)->names('transaksi.pengeluaran');

    Route::resource('mobil',MobilController::class);
    Route::resource('kota',KotaController::class);
    Route::resource('jasa',JasaController::class);
    Route::resource('bank',BankController::class);
    Route::resource('driverfee',DriverfeeController::class);


    Route::get('/getphoto', [InventoryController::class, 'getphoto']);
    Route::get('/getcustomer', [CustomerController::class, 'getcustomer']);
    Route::get('/getinventory', [InventoryController::class, 'getinventory']);
    Route::get('/cetakinv/{no_inv}', [InvoiceController::class, 'cetak']);

    Route::get('/pengembalian/{order_id}', [OrderController::class, 'pengembalian']);
    Route::get('/invoicing/{id}', [PengembalianController::class, 'invoicing'])->name('report.invoicing');
});

app/Models/Driverfee.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Driverfee extends Model
{
    use HasFactory;
}

app/Http/Controllers/DriverfeeController.php
<?php

namespace App\Http\Controllers;

use App\Models\Driverfee;
use Illuminate\Http\Request;

class DriverfeeController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        
        $dataList = Driverfee::all();
      
        $dt = [
            'menu' => 'Data Harga Driver',
            'title' => 'List Harga Driver', 
        ];
       
        return view('driverfee.index', compact('dt','dataList'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $dt = [
            'menu' => 'Kelola Harga Driver',
            'title' => 'Tambah Harga Driver Baru',
            
            
        ];
       
        return view('driverfee.create', compact('dt'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $rules = [
            
            'judul'     => 'required',
            'durasi'      => 'required',
            'harga'     => 'required',
            'order'     => 'required',
            
            

		];

		$errorMessages = [
            'required' => 'Kolom harus diisi',
        ];

        $this->validate($request, $rules, $errorMessages);

        $data = new Driverfee();

        $data->judul = $request->judul;
        $data->durasi = $request->durasi;
        $data->harga = $request->harga;
        $data->order = $request->order;
        
    

        $data->save();

        return redirect()->route('driverfee.index')->with('success', 'Data harga driver berhasil disimpan');
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $data = Driverfee::find($id);

        $dt = [
            'menu' => 'Kelola Harga Driver ',
            'title' => 'Edit Harga Driver  ',
            
        ];
       

        return view('driverfee.edit', compact('dt','data'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $data = Driverfee::find($id);

        $rules = [
            
            'judul'     => 'required',
            'durasi'      => 'required',
            'harga'     => 'required',
            'order'     => 'required',
            
            

		];

		$errorMessages = [
            'required' => 'Kolom harus diisi',
        ];

        $this->validate($request, $rules, $errorMessages);

        $data->judul = $request->judul;
        $data->durasi = $request->durasi;
        $data->harga = $request->harga;
        $data->order = $request->order;
        
    

        $data->save();

        return redirect()->route('driverfee.index')->with('success', 'Data harga driver berhasil diperbaharui');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        $data = Driverfee::find($id);
        $data->delete();

        return redirect()->route('driverfee.index')->with('success', 'Data harga driver berhasil dihapus');
    }
}

resources/views/driverfee/create.blade.php
@extends('shared_pages.layout')
@section('content')
    <div class="card">
        <div class="card-header">
            <h5>{{ $dt['title'] }}</h5>
        </div>
        <div class="card-body">
            <form action="{{ route('driverfee.store') }}" name="myForm" method="POST" onsubmit="return validateForm()">
                @csrf
                @method('POST')
                <!-- Page Heading -->
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <div class="d-sm-flex">
                        <a href="{{ route('driverfee.index') }}" class="btn btn-md btn-circle btn-outline-danger">
                            <i class="bi bi-skip-backward-fill"></i> Back
                        </a>
                        &nbsp;
                    </div>
                    {{-- <button type="submit" class="btn btn-outline-success btn-md btn-icon-split">
                        Submit Order <i class="bi bi-sd-card-fill"></i>
                    </button> --}}
                </div>

                <!-- content -->
                <div class="row">
             
                    <div class="col-lg-12">
                        <div class="card border-bottom-primary shadow mb-4">
                            <div class="card-header py-3 bg-orange">
                                <h6 class="m-0 font-weight-bold text-white">Data Harga Driver</h6>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                   
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Judul</label>
                                            <input type="text" class=" form-control @error('judul') is-invalid @enderror" name="judul" value="{{ old('judul') }}">
                                            @error('judul')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Durasi</label>
                                            <input type="text" class=" form-control @error('durasi') is-invalid @enderror" name="durasi" value="{{ old('durasi') }}">
                                            @error('durasi')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Harga</label>
                                            <input type="text" class=" form-control @error('harga') is-invalid @enderror" name="harga" value="{{ old('harga') }}">
                                            @error('harga')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Urutan</label>
                                            <input type="text" class=" form-control @error('order') is-invalid @enderror" name="order" value="{{ old('order') }}">
                                            @error('order')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                    
                                  
                                </div>

                                <button type="submit" class="btn btn-outline-success btn-md btn-icon-split">
                                    Submit Jasa <i class="bi bi-sd-card-fill"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                  
                </div>
            </form>
        </div>
    </div>
    <script>
       
    </script>
@endsection

resources/views/driverfee/edit.blade.php
@extends('shared_pages.layout')
@section('content')
    <div class="card">
        <div class="card-header">
            <h5>{{ $dt['title'] }}</h5>
        </div>
        <div class="card-body">
            <form action="{{ route('driverfee.update',$data->id) }}" name="myForm" method="POST" onsubmit="return validateForm()">
                @csrf
                @method('PATCH')
                <!-- Page Heading -->
                <div class="d-sm-flex align-items-center justify-content-between mb-4">
                    <div class="d-sm-flex">
                        <a href="{{ route('driverfee.index') }}" class="btn btn-md btn-circle btn-outline-danger">
                            <i class="bi bi-skip-backward-fill"></i> Back
                        </a>
                        &nbsp;
                    </div>
                    {{-- <button type="submit" class="btn btn-outline-success btn-md btn-icon-split">
                        Submit Order <i class="bi bi-sd-card-fill"></i>
                    </button> --}}
                </div>

                <!-- content -->
                <div class="row">
             
                    <div class="col-lg-12">
                        <div class="card border-bottom-primary shadow mb-4">
                            <div class="card-header py-3 bg-orange">
                                <h6 class="m-0 font-weight-bold text-white">Data harga Driver </h6>
                            </div>
                            <div class="card-body">
                                <div class="row">
                                  
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Judul</label>
                                            <input type="text" class=" form-control @error('judul') is-invalid @enderror" name="judul" value="{{ old('judul') ? old('judul') : $data->judul }}">
                                            @error('judul')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Durasi</label>
                                            <input type="text" class=" form-control @error('durasi') is-invalid @enderror" name="durasi" value="{{ old('durasi') ? old('durasi') : $data->durasi }}">
                                            @error('durasi')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Harga</label>
                                            <input type="text" class=" form-control @error('harga') is-invalid @enderror" name="harga" value="{{ old('harga') ? old('harga') : $data->harga }}">
                                            @error('harga')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>

                                    <div class="col-lg-6">
                                        <div class="form-group">
                                            <label class="mt-2">Urutan</label>
                                            <input type="text" class=" form-control @error('order') is-invalid @enderror" name="order" value="{{ old('order') ? old('order') : $data->order }}">
                                            @error('order')
                                                <div class="invalid-feedback">
                                                    {{ $message }}
                                                </div>
                                            @enderror
                                        </div>
                                    </div>
                                    
                                  
                                </div>

                                <button type="submit" class="btn btn-outline-success btn-md btn-icon-split">
                                    Submit Jasa <i class="bi bi-sd-card-fill"></i>
                                </button>
                            </div>
                        </div>
                    </div>
                  
                </div>
            </form>
        </div>
    </div>
    <script>
       
    </script>
@endsection

resources/views/driverfee/index.blade.php
@extends('shared_pages.layout')
@section('content')
    <section class="section">
        <div class="card">
            <div class="card-header text-end">
                <h4>{{ $dt['title'] }}</h4>
            </div>
            <div class="card-body">
                @if ($message = Session::get('success'))
                    <div class="mb-3 pl-3 pr-3">
                        <div class="alert alert-success alert-dismissible show fade">
                            <i class="far fa-fw fa-bell"></i> {{ $message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                @endif
                @can('peminjaman-create')
                    <a href="{{ route('driverfee.create') }}" class="btn btn-outline-success mb-5">
                        <i class="bi bi-plus-circle"></i> Buat Harga Driver Baru
                    </a>
                @endcan
                <div class="table-responsive">
                    <table class="table" id="table1">
                        <thead>
                            <tr class="bg-orange text-light">
                                <th>No</th>
                                <th>Judul</th>
                                <th>Durasi</th>
                                <th>Harga</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            <?php $k = 0; ?>
                            @forelse ($dataList as $p)
                                <tr>
                                    <td>{{ $p->order }}</td>
                                    <td>{{ $p->judul }}</td>
                                   
                                    <td>{{ $p->durasi }}</td>
                                    <td>{{ number_format($p->harga,0,'','.') }}</td>
                                   
                                   
                                    
                                    <td>

                                        <div class="d-flex">

                                            <a class="btn btn-sm btn-primary me-1" href="{{ route('driverfee.edit', $p->id) }}"
                                                title="Edit Customer"><i class="bi bi-pencil"></i></a>
                                           
                                            <form onsubmit="return confirm('Benar akan meghapus data ini ?')"
                                                action="{{ route('driverfee.destroy', $p->id) }}" method="POST">
                                                @csrf
                                                @method('DELETE')
                                                
                                                    <button type="submit" class="btn btn-sm btn-danger" title="Delete"><i
                                                            class="bi bi-x"></i></button>
                                                
                                            </form>

                                        </div>
                                        
                                    </td>
                                </tr>
                                <?php $k++; ?>
                            @empty
                                <tr>
                                    <td colspan="7" class="text-danger text-center">Data order rental belum ada</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
    <script>
       
    </script>
@endSection