routes/web.php
<?php

use App\Http\Controllers\AdminPemesananController;
use App\Http\Controllers\BankController;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\HomeController;
use App\Http\Controllers\MenuController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\OrderController;
use App\Http\Controllers\ReportController;
use App\Http\Controllers\InvoiceController;
use App\Http\Controllers\PaymentController;
use App\Http\Controllers\CustomerController;
use App\Http\Controllers\DriverfeeController;
use App\Http\Controllers\FrontController;
use App\Http\Controllers\InventoryController;
use App\Http\Controllers\JasaController;
use App\Http\Controllers\KategoriPemasukanController;
use App\Http\Controllers\KategoriPengeluaranController;
use App\Http\Controllers\KotaController;
use App\Http\Controllers\MobilController;
use App\Http\Controllers\PeminjamanController;
use App\Http\Controllers\PengembalianController;
use App\Http\Controllers\RentalController;
use App\Http\Controllers\TransaksiPemasukanController;
use App\Http\Controllers\TransaksiPengeluaranController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/

Auth::routes();
Route::get('/', [FrontController::class, 'pemesanan'])->name('home');

Route::get('/fetch-durasi', [RentalController::class, 'durasiFetch'])->name('durasiFetch');

Route::get('/service/rental', [RentalController::class, 'mobil'])->name('rental.mobil');
Route::get('/service/rental/pemesanan', [RentalController::class, 'pemesanan'])->name('rental.pemesanan');
Route::post('/service/rental/pemesanan/store', [FrontController::class, 'storePemesanan'])->name('rental.pemesanan.store');
Route::get('//service/rental/pemesanan/detail', [FrontController::class, 'detailPemesanan'])->name('rental.pemesanan.detail');


Route::get('/fganti_psswrd', [HomeController::class, 'fganti_psswrd'])->name('fganti_psswrd');
Route::put('/update_psswrd/{user}', [HomeController::class, 'update_psswrd'])->name('update_psswrd');

Route::group(['middleware' => ['auth']], function () {

    Route::get('/home', [HomeController::class, 'home'])->name('home');

    Route::get('/profile', [HomeController::class, 'profile'])->name('profile');

    Route::get('/laporan/', [ReportController::class, 'index'])->name('laporan.index');

    Route::get('/pemesanan/', [AdminPemesananController::class, 'index'])->name('pemesanan.index');
    Route::get('/pemesanan/{id}/detail', [AdminPemesananController::class, 'detail'])->name('pemesanan.detail');

    Route::resource('roles', RoleController::class);
    Route::resource('users', UserController::class);
    // Route::resource('menu', MenuController::class);
    Route::resource('customer', CustomerController::class);
    Route::resource('inventory', InventoryController::class);
    Route::resource('order', OrderController::class);
    Route::resource('finishorder', PengembalianController::class);
    Route::resource('invoice', InvoiceController::class);

    Route::resource('kategori/pemasukan', KategoriPemasukanController::class)->names('kategori.pemasukan');
    Route::resource('kategori/pengeluaran', KategoriPengeluaranController::class)->names('kategori.pengeluaran');

    Route::resource('transaksi/pemasukan', TransaksiPemasukanController::class)->names('transaksi.pemasukan');
    Route::resource('transaksi/pengeluaran', TransaksiPengeluaranController::class)->names('transaksi.pengeluaran');

    Route::resource('mobil',MobilController::class);
    Route::resource('kota',KotaController::class);
    Route::resource('jasa',JasaController::class);
    Route::resource('bank',BankController::class);
    Route::resource('driverfee',DriverfeeController::class);


    Route::get('/getphoto', [InventoryController::class, 'getphoto']);
    Route::get('/getcustomer', [CustomerController::class, 'getcustomer']);
    Route::get('/getinventory', [InventoryController::class, 'getinventory']);
    Route::get('/cetakinv/{no_inv}', [InvoiceController::class, 'cetak']);

    Route::get('/pengembalian/{order_id}', [OrderController::class, 'pengembalian']);
    Route::get('/invoicing/{id}', [PengembalianController::class, 'invoicing'])->name('report.invoicing');
});

app/Models/Customer.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Customer extends Model
{
    use HasFactory;
    protected $table = 'customer';
    protected $guarded = ['created_at', 'updated_at'];
    public function user()
    {
        return $this->belongsTo(User::class);
    }

    public function kotaCustomer()
    {
        return $this->belongsTo(Kota::class,'kota_id','id');
    }
}

app/Http/Controllers/CustomerController.php
<?php

namespace App\Http\Controllers;

use App\Models\Menu;
use App\Models\User;
use App\Models\Customer;
use Illuminate\View\View;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Kota;
use Illuminate\Support\Facades\Auth;
use Illuminate\Http\RedirectResponse;
use Illuminate\Support\Str;

class CustomerController extends Controller
{
    function __construct()
    {
        $this->middleware('permission:customer-list|customer-create|customer-edit|customer-delete', ['only' => ['index', 'show']]);
        $this->middleware('permission:customer-create', ['only' => ['create', 'store']]);
        $this->middleware('permission:customer-edit', ['only' => ['edit', 'update']]);
        $this->middleware('permission:customer-delete', ['only' => ['destroy']]);
    }
    public function index(): View
    {
        // cek role user yg login
        $customer = [];
        $role = Auth::user()->roles->pluck('name')[0];
        if ($role == 'Admin') {
            $customer = Customer::with('kotaCustomer')->get();
        } else {
            $customer = Customer::with('kotaCustomer')->where('user_id', Auth::user()->id)->get();
        }
        $dt = [
            'menu' => 'Kelola Customer',
            'title' => 'List customer',
            'customer' => $customer,
        ];
        $menu = [
            'menu' => Menu::all()->sortBy('urutan'),
        ];
        return view('customer.index', compact('dt', 'menu'));
    }
    public function create(): View
    {
        // cek role user yg login
       
        $dt = [
            'menu' => 'Kelola Customer',
            'title' => 'Tambah Customer Baru',
           
        ];

        $kotaList = Kota::all();
        
        return view('customer.create', compact('dt', 'kotaList'));
    }
    public function store(Request $request): RedirectResponse
    {
        $rules = [
            'nik'      => 'required|numeric|digits:16',
           
            'nama' => 'required',
            'alamat' => 'required',
            'telp' => 'required',
            'kota' => 'required',
        ];
        
        $errorMessages = [
            'numeric' => 'Nomor NIK harus diisi dengan angka',
            'digits' => 'Nomor NIK harus  berjumlah 16 angka',
            'nik.required' => 'belum diisi',
            'kota.required' => 'belum diisi',
            'nama.required' => 'belum diisi',
            'alamat.required' => 'belum diisi',
            'telp.required' => 'belum diisi',
            'pic.required' => 'belum diisi',
        ];

        $this->validate($request, $rules, $errorMessages);

        $telp = $request->telp;

        $nta = Str::is('0*', $telp);
        $ntb = Str::is('62*', $telp);

        if($nta){
            $slice = Str::after($telp,'0');
            $wa = '62'.$slice;
        }

        if($ntb){
            $wa = $telp;
        }

        $data = new Customer();

        $data->nik = $request->nik;
        $data->nama = $request->nama;
        $data->alamat = $request->alamat;
        $data->telp = $wa;
        $data->kota_id = $request->kota;
        $data->user_id = 0;

        $data->save();
        
        
        return redirect()->route('customer.index')->with('success', 'Data customer berhasil disimpan');
        
    }
    public function edit(customer $customer): View
    {
        // cek role user yg login
       
        $dt = [
            'menu' => 'Kelola Customer',
            'title' => 'Edit Data customer',
            'customer' => $customer,
            
        ];
        $kotaList = Kota::all();
        return view('customer.edit', compact('dt', 'kotaList'));
    }
    public function update(Request $request, $id): RedirectResponse
        { 
        
            $data = Customer::find($id);
        
            $rules = [
                'nik'      => 'required|numeric|digits:16',
            
                'nama' => 'required',
                'alamat' => 'required',
                'telp' => 'required',
                'kota' => 'required',
            ];
            
            $errorMessages = [
                'numeric' => 'Nomor NIK harus diisi dengan angka',
                'digits' => 'Nomor NIK harus  berjumlah 16 angka',
                'nik.required' => 'belum diisi',
                'kota.required' => 'belum diisi',
                'nama.required' => 'belum diisi',
                'alamat.required' => 'belum diisi',
                'telp.required' => 'belum diisi',
                'pic.required' => 'belum diisi',
            ];

            $this->validate($request, $rules, $errorMessages);

            $telp = $request->telp;

            $nta = Str::is('0*', $telp);
            $ntb = Str::is('62*', $telp);

            if($nta){
                $slice = Str::after($telp,'0');
                $wa = '62'.$slice;
            }

            if($ntb){
                $wa = $telp;
            }

            

            $data->nik = $request->nik;
            $data->nama = $request->nama;
            $data->alamat = $request->alamat;
            $data->telp = $wa;
            $data->kota_id = $request->kota;
            $data->user_id = 0;

            $data->save();
            
            
            return redirect()->route('customer.index')->with('success', 'Data customer berhasil disimpan');

        }
    public function destroy(Customer $customer): RedirectResponse
    {
        $customer->delete();
        return redirect()->route('customer.index')->with('success', 'Data customer berhasil dihapus');
    }
    public function getcustomer(Request $request)
    {
        $customer = Customer::findOrFail($request->id);
        return response()->json([
            'berhasil' => true,
            'customer' => $customer,
        ]);
    }
}

app/View/Components/Stats/Customer.php
<?php

namespace App\View\Components\Stats;

use App\Models\Customer as ModelsCustomer;
use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Customer extends Component
{
    /**
     * Create a new component instance.
     */
    public $total;
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        $this->total = ModelsCustomer::count();
        return view('components.stats.customer');
    }
}

resources/views/customer/create.blade.php
@extends('shared_pages.layout')
@section('content')
    <div class="card">
        <div class="card-header">
            <h5>{{ $dt['title'] }}</h5>
        </div>
        <div class="card-body">
            <form class="forms-sample" action="{{ route('customer.store') }}" method="POST">
                @csrf
                @method('post')

                <div class="row form-group">
                    <div class="col-sm-12">
                        <label>NIK</label>
                        <div class="input-group mb-3">
                            
                            <input type="text" class="form-control @error('nik') is-invalid @enderror" name="nik"
                                value="{{ old('nik') }}" placeholder="NIK customer" autofocus>
                            @error('nik')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                </div>
               
                <div class="row form-group">
                    <div class="col-sm-12">
                        <label>Nama Customer</label>
                        <div class="input-group mb-3">
                            
                            <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama"
                                value="{{ old('nama') }}" placeholder="Nama customer" autofocus>
                            @error('nama')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-12">
                        <label>Telp</label>
                        <div class="input-group mb-3">
                            
                            <input type="text" class="form-control @error('telp') is-invalid @enderror" name="telp"
                                value="{{ old('telp') }}">
                            @error('telp')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-12">
                        <label>Kota</label>
                        <div class="input-group mb-3">
                            
                            <select type="text" class="form-control @error('kota') is-invalid @enderror"
                                name="kota" value="{{ old('kota') }}">
                                <option value="">-- Pilih Kota --</option>
                                @foreach ($kotaList as $p)
                                    <option value="{{ $p->id }}">{{ $p->kota }}</option>
                                @endforeach
                            </select>
                            @error('kota')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-sm-12">
                        <label>Alamat Customer</label>
                        <div class="input-group mb-3">
                            
                            <input type="text" class="form-control @error('alamat') is-invalid @enderror" name="alamat"
                                value="{{ old('alamat') }}" id="formFile">
                            @error('alamat')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                </div>
               
                <div class="row justify-content-between">
                    <div class="col">
                        <a href="{{ route('customer.index') }}" class="btn btn-secondary">Kembali</a>
                    </div>
                    <div class="col text-end">
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/customer/edit.blade.php
@extends('shared_pages.layout')
@section('content')
    <div class="card">
        <div class="card-header">
            <h5>{{ $dt['title'] }}</h5>
        </div>
        <div class="card-body">
            <form class="forms-sample" action="{{ route('customer.update', $dt['customer']->id) }}" method="POST"
                enctype="multipart/form-data">
                @csrf
                @method('put')
                <div class="row form-group">
                    <div class="col-sm-12">
                        <label>NIK</label>
                        <div class="input-group mb-3">
                            
                            <input type="text" class="form-control @error('nik') is-invalid @enderror" name="nik"
                                value="{{ $dt['customer']->nik }}" placeholder="NIK customer" autofocus>
                            @error('nik')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-12">
                        <label>Nama Customer</label>
                        <div class="input-group mb-3">
                           
                            <input type="text" class="form-control @error('nama') is-invalid @enderror" name="nama"
                                value="{{ $dt['customer']->nama }}" placeholder="Nama customer" autofocus>
                            @error('nama')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-12">
                        <label>Alamat Customer</label>
                        <div class="input-group mb-3">
                           
                            <input type="text" class="form-control @error('alamat') is-invalid @enderror" name="alamat"
                                value="{{ $dt['customer']->alamat }}" id="formFile">
                            @error('alamat')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                </div>
                <div class="row form-group">
                    <div class="col-sm-12">
                        <label>Telp</label>
                        <div class="input-group mb-3">
                           
                            <input type="text" class="form-control @error('telp') is-invalid @enderror" name="telp"
                                value="{{ $dt['customer']->telp }}">
                            @error('telp')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                </div>

                <div class="row form-group">
                    <div class="col-sm-12">
                        <label>Kota</label>
                        <div class="input-group mb-3">
                            
                            <select type="text" class="form-control @error('kota') is-invalid @enderror"
                                name="kota" value="{{ old('kota') }}">
                                <option value="">-- Pilih Kota --</option>
                                @foreach ($kotaList as $p)
                                    <option {{$p->id ==  $dt['customer']->kota_id ? 'selected' : '' }} value="{{ $p->id }}">{{ $p->kota }}</option>
                                @endforeach
                            </select>
                            @error('kota')
                                <div class="invalid-feedback">
                                    {{ $message }}
                                </div>
                            @enderror
                        </div>
                    </div>
                </div>
                
               
                <div class="row justify-content-between">
                    <div class="col">
                        <a href="{{ route('customer.index') }}" class="btn btn-secondary">Kembali</a>
                    </div>
                    <div class="col text-end">
                        <button type="submit" class="btn btn-primary">Update</button>
                        <button type="reset" class="btn btn-danger">Reset</button>
                    </div>
                </div>
            </form>
        </div>
    </div>
@endsection

resources/views/customer/index.blade.php
@extends('shared_pages.layout')
@section('content')
    <section class="section">
        <div class="card">
            <div class="card-header text-end">
                <h4>{{ $dt['title'] }}</h4>
            </div>
            <div class="card-body">
                @if ($message = Session::get('success'))
                    <div class="mb-3 pl-3 pr-3">
                        <div class="alert alert-success alert-dismissible show fade">
                            <i class="far fa-fw fa-bell"></i> {{ $message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    </div>
                @endif
                <a href="{{ route('customer.create') }}" class="btn btn-outline-success mb-5">
                    <i class="bi bi-plus-circle"></i> Tambah Customer Baru
                </a>
                <div class="table-responsive">
                    <table class="table" id="table1">
                        <thead>
                            <tr class="bg-orange text-light">
                                <th>No</th>
                                <th>NIK</th>
                                <th>Nama Customer</th>
                                <th>Alamat</th>
                                <th>Telp</th>
                                <th>kota</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                        <tbody>
                            @forelse ($dt['customer'] as $p)
                                <tr>
                                    <td>{{ $loop->iteration }}</td>
                                    <td>{{ $p->nik }}</td>
                                    <td>{{ $p->nama }}</td>
                                    <td>{{ $p->alamat }}</td>
                                    <td>{{ $p->telp }}</td>
                                    <td>{{ $p->kotaCustomer->kota }}</td>
                                 
                                    <td>
                                        <form onsubmit="return confirm('Benar akan meghapus data ini ?')"
                                            action="{{ route('customer.destroy', $p->id) }}" method="POST">
                                            @can('customer-edit')
                                                <a class="btn btn-sm btn-primary" href="{{ route('customer.edit', $p->id) }}"
                                                    title="Edit Customer"><i class="bi bi-pencil"></i></a>
                                            @endcan
                                            @csrf
                                            @method('DELETE')
                                            @can('customer-delete')
                                                <button type="submit" class="btn btn-sm btn-danger" title="Delete Customer"><i
                                                        class="bi bi-x"></i></button>
                                            @endcan
                                        </form>
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7" class="text-danger text-center">Data customer belum ada</td>
                                </tr>
                            @endforelse
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </section>
@endSection